language: java
sudo: false

jdk:
  - openjdk8
  - openjdk11

cache:
  directories:
  - $HOME/.m2

install:
  - mvn clean install -DskipTests=true -Dmaven.javadoc.skip=true -B -V

script:
  - sh ./.middleware-common/check_format.sh

after_success:
  - travis_retry mvn clean test